ELFMS/requestManager/urls.py
from django.conf.urls import patterns, url

from requestManager import views

urlpatterns = patterns('',
    url(r'^$', views.reqManager, name='request'),
    url(r'^(?P<resource_id>\d+)/$', views.detail, name='detail'),
)

ELFMS/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
urlpatterns = patterns('',
    # Examples:
    url(r'^$', "login.views.login", name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^request/', include('requestManager.urls', namespace="request")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', include('login.urls')),
    url(r'^userprofile/', include('userprofile.urls')),

)
admin.autodiscover()

requestManager/urls.py
from django.conf.urls import patterns, url

from requestManager import views

urlpatterns = patterns('',
    url(r'^$', views.reqManager, name='request'),
    url(r'^(?P<resource_id>\d+)/$', views.detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.edit, name='edit'),
    url(r'^create/$', views.createRequest, name='create'),
    url(r'^success/$', views.createSuccess, name='createSuccess'),
    url(r'^search/$', views.search, name='search'),
)

ELFMS/requestManager/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class resource(models.Model):
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=50)
    edition = models.CharField(max_length=50)
    subscription_type = models.BooleanField(default=True)
    pub_year = models.IntegerField(default=0)
    creation_date = models.DateTimeField(default=datetime.now)
    tag= models.IntegerField(default=1)
    comment = models.CharField(max_length=200)
    #add foreignkey for model ni user from loginapp
    
    def __unicode__(self):
        return self.title

requestManager/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class resource(models.Model):
    title = models.CharField('Title', max_length=50)
    author = models.CharField('Author', max_length=50)
    edition = models.CharField('Edition', max_length=50)
    subscription_type = models.BooleanField(default=False)
    pub_year = models.IntegerField(default=0)
    price = models.DecimalField('Price', null = True, max_digits = 8, decimal_places = 2)
    creation_date = models.DateTimeField(default=datetime.now)
    approved = models.BooleanField(default=False)
    comment = models.CharField(max_length=200, default='')
    #add foreignkey for model ni user from loginapp
    
    # class Meta:
    #     unique_together = ('title', 'edition',)

    def __unicode__(self):
        return self.title

requestManager/forms.py
from django.db.models import Q
from simple_search import BaseSearchForm
from django import forms
from django.forms import ModelForm
from requestManager.models import resource


class resourceForm(ModelForm):
    comment = forms.CharField(required=False)
    price = forms.DecimalField(required=False)
    class Meta:
        model = resource
        fields = '__all__'

class resourceSearchForm(BaseSearchForm):
	class Meta:
		base_qs = resource.objects
		search_fields = ('title','^author', '=id')
		#fulltext_indexes = (('title', 2), ('title, author, id', 1),)

ELFMS/requestManager/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from requestManager.models import resource

# Create your views here.
def reqManager(request):
    latest_request = resource.objects.order_by('-creation_date')[:10]
    context = {'latest_request': latest_request}
    return render(request, 'requestManager/index.html', context)
    
def detail(request, resource_id):
    r = get_object_or_404(resource, pk=resource_id)
    return render(request, 'requestManager/detail.html', {'r': r})

requestManager/views.py
from django.shortcuts import render, get_object_or_404, render_to_response, redirect
from django.http import HttpResponse, HttpResponseRedirect
from requestManager.models import resource
from django.template import RequestContext
from requestManager.forms import resourceForm, resourceSearchForm
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/login/')
def reqManager(request):
    latest_request = resource.objects.order_by('title')[:10]
    context = {'latest_request': latest_request}
    return render(request, 'requestManager/index.html', context)
    
def detail(request, resource_id):
    r = get_object_or_404(resource, pk=resource_id)
    return render(request, 'requestManager/detail.html', {'r': r})

def createRequest(request):
	if request.method == 'POST':
		form = resourceForm(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.save()
			red = "/request/" + str(post.id) + "/"
			return redirect(red)
	else:
		print "get method"
		form = resourceForm()
	return render(request, 'requestManager/create.html', {'form':form})

def createSuccess(request, resource_id):
	return render(request, 'requestManager/success.html')

def search(request):
	if request.GET:
		print "yes get"
		form = resourceSearchForm(request.GET)
		if form.is_valid():
			print "form is_valid"
			results = form.get_result_queryset()
			print results
		else:
			results = []
	else:
		form = resourceSearchForm()
		results = []

	return render_to_response('requestManager/search.html',RequestContext(request, {'form':form, 'results': results,}))

def edit(request, pk):
    post = get_object_or_404(resource, pk=pk)
    if request.method == "POST":
        form = resourceForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            #post.author = request.user
            post.save()
            red = "/request/"+str(post.id)+"/"
            return redirect(red)
    else:
        form = resourceForm(instance=post)
    return render(request, 'requestManager/create.html', {'form': form})

requestManager/templates/requestManager/create.html
{% block content %}

	<h2> Make Request</h2>

	{% for field in form %}
		{{field.error}}

	{% endfor %}

	<form method ="POST"> 
		{%csrf_token%}
		{{form.as_ul}}

		<button type="submit">Save</button>
	</form>
{% endblock %}

requestManager/templates/requestManager/detail.html
<h1>{{ r.title }}</h1>
<p> Author: {{ r.author }}</p>
<p> Edition: {{ r.edition }}</p>
<p> Subscription Type: {{ r.subscription_type }}</p>
<p> Publication Year: {{ r.pub_year }}</p>
<p> Price: {{ r.price }}</p>
<p> Approved: {{ r.approved }}</p>
<p> Creation Date: {{ r.creation_date }}</p>
<p> Comment: {{ r.comment }}</p>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<a href="{% url 'request:edit' r.id %}">edit</a>
<a href="{% url 'request:request' %}">View all requests</a>

requestManager/templates/requestManager/index.html
<a href="{% url 'request:create' %}"> create request </a>
{% if latest_request %}
    <table style ='width:100%'>
    	<tr>
    		<td>Title</td>
    		<td>Author</td>
    		<td>Edition</td>
    		<td>Year</td>
    		<td>Price</td>
    		<td>Approved</td>
    	</tr>
    {% for resource in latest_request %}
    	<tr>
    		<td><a href="{% url 'request:detail' resource.id %}">{{ resource.title }}</a></td>
    		<td>{{resource.author}}</td>
    		<td>{{resource.edition}}</td>
    		<td>{{resource.pub_year}}</td>
    		<td>{{resource.price}}</td>
    		<td>{{resource.approved}}</td>
    		
    	</tr>
    {% endfor %}
{% else %}
    <p>No resources are available.</p>
{% endif %}

<form action="{% url 'request:search' %}" method ="GET"> 
	<input type="text" name="q">
	<input type="submit" value="Search">
</form>

<ul>
    {% for resource in results %}
        <li><a href="{% url 'request:detail' resource.id %}">{{ resource.title }}</a></li>
    {% endfor %}
</ul>

requestManager/templates/requestManager/index2.html
<ul>
    {% for resource in results %}
        <li><a href="{% url 'request:detail' resource.id %}">{{ resource.title }}</a></li>
    {% endfor %}
</ul>

requestManager/templates/requestManager/search.html
<form action="{% url 'request:search' %}" method ="GET"> 
	<input type="text" name="q">
	<input type="submit" value="Search">
</form>

<ul>
    {% for resource in results %}
        <li><a href="{% url 'request:detail' resource.id %}">{{ resource.title }}</a></li>
    {% endfor %}
</ul>

requestManager/templates/requestManager/success.html
{% block content %}

	<h2>Request successful</h2>
 	<a href="{% url 'request:create' %}">Create Request</a> 
  	<a href="{% url 'request:request' %}">View all requests</a>

{% endblock %}